"""Initial

Revision ID: 05dd2b335ed5
Revises: 
Create Date: 2025-06-23 23:47:43.452925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05dd2b335ed5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retroboard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retroboard_name'), 'retroboard', ['name'], unique=False)
    op.create_table('retrocolumn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['retroboard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retro_column_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['retro_column_id'], ['retrocolumn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    op.drop_table('retrocolumn')
    op.drop_index(op.f('ix_retroboard_name'), table_name='retroboard')
    op.drop_table('retroboard')
    # ### end Alembic commands ###
