"""Initial commit

Revision ID: 8d35c88b0cde
Revises: 
Create Date: 2025-06-21 03:43:28.346733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d35c88b0cde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retro_column_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['retro_column_id'], ['retrocolumn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('retrocolumn', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('retrocolumn', sa.Column('board_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'retrocolumn', 'retroboard', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'retrocolumn', type_='foreignkey')
    op.drop_column('retrocolumn', 'board_id')
    op.drop_column('retrocolumn', 'content')
    op.drop_table('topic')
    # ### end Alembic commands ###
