
services:
  api:
    build: ./app
    ports:
      - "8080:80"
    tty: true

  db:
    image: postgres:17.5
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=retrome_db