
services:
  web:
    build: ./app
    ports:
      - "8080:80"
    tty: true
    restart: on-failure
    volumes:
      - ./app:/code/app
    env_file:
      - ./app/.env

  db:
    image: postgres:17.5
    restart: unless-stopped
    container_name: db
    expose:
      - 5432
    env_file:
      - ./app/.env
    volumes:
      - ./db:/var/lib/postgresql/data
