
services:
  web:
    build: ./app
    ports:
      - "8080:80"
    tty: true
    restart: on-failure
    volumes:
      - ./app:/code/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432

  db:
    image: postgres:17.5
    restart: unless-stopped
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=retrome_db
    volumes:
      - ./db:/var/lib/postgresql/data
